### ISSUE TITLE
SCSS file error

### ISSUE THREAD

**Issue by Ajnx10** [carbon-design-system/carbon-addons-infrastructure#36]
I have installed this again but facing issues while importing the `scss` file into my project.

I have imported using `@import "~carbon-addons-infrastructure/scss/index";` but getting the below error. It may be an issue in importing the `carbon-components` library in scss files. Please look on it. 

<img width="1167" alt="screen shot 2018-12-13 at 1 10 03 pm" src="https://user-images.githubusercontent.com/45667905/49961719-fd3fad80-fed8-11e8-973a-0165c5945324.png">

**Comment by Ajnx10** [comment]
Can you pls look into this its urgent.
Thanks in advance.

**Comment by asudoh** [comment]
Hi 👋 would you try [`includePath`](https://github.com/sass/node-sass#includepaths) setting in Sass building tool? Thanks!

**Comment by Ajnx10** [comment]
I got this issue working. 

Thanks...!!!

**Comment by asudoh** [comment]
:+1:
